models train module and inference service
crypto-sentiment/crypto_sentiment_demo_app pull request #2
Opened 2022-05-05 18:50 UTC by aleksandrinvictor

- Update models inference service. Any model with proper interface can be added to model registry.
- Add train module that can be launched with docker compose to obtain model checkpoints.
- Replace config file with hydra configs
- Update docker-compose file in the following way:
    1. All services are separated on two profiles to support train module
    2. Model scorer and frontend don't launch until inference service is up. depends_on parameter allows to set launch order but for example inference service with bert model takes several minutes to download weights from huggingface. That leads to a situation where frontend run out of connection trials trying to connect to inference service. That's why we have to add a healthcheck pinging inference service and wait until it launches and only then launch frontend and model scorer.

2022-05-06 09:33 UTC, Arsenaut commented on crypto_sentiment_demo_app/model_inference_api/Dockerfile
> +    && apt update && apt install nano
Видимо, при тестировании добавил установку nano, чтобы можно было конфиги "на живую" поменять в контейнере, и забыл выпилить. Я угадал? :'D
Давай либо выпилим nano, либо поменяем со строкой выше местами, чтобы apt cache не тащить в образ?

2022-05-06 09:33 UTC, Arsenaut commented on crypto_sentiment_demo_app/model_inference_api/Dockerfile
> +RUN curl -sLo ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh \
Нам точно миниконда нужна в контейнере таком? Кажется, что она немного раздувает и так довольно большой образ

2022-05-06 09:33 UTC, Arsenaut commented on crypto_sentiment_demo_app/models/base.py
> +    def get_model(cls, name: str, cfg: Dict[str, Any]) -> "ModelEngine":
Возвращаемый тип видимо случайно в строку превратился

2022-05-06 09:33 UTC, Arsenaut commented on crypto_sentiment_demo_app/models/bert/model.py
> +        if self.cfg["device"] == "gpu" and not torch.cuda.is_available():
Да можно просто наверное проверку на `torch.cuda.is_available()`?
`self.device = "gpu" if torch.cuda.is_available() else "cpu"`

2022-05-06 09:33 UTC, Arsenaut commented on conf/model/bert.yaml
> +        padding: True
Давай, может, ещё аргумент `return_tensors: pt` добавим сразу, чтобы потом не конвертировать в торчевский тензор каждый раз самому?

2022-05-06 09:33 UTC, Arsenaut commented on crypto_sentiment_demo_app/train/Dockerfile
> +    && apt update && apt install nano
Тут то же самое про nano :'D

2022-05-09 05:33 UTC, aleksandrinvictor commented on crypto_sentiment_demo_app/model_inference_api/Dockerfile
> +    && apt update && apt install nano
fixed in 9620a5c

2022-05-09 05:34 UTC, aleksandrinvictor commented on crypto_sentiment_demo_app/train/Dockerfile
> +    && apt update && apt install nano
fixed in 9620a5c

2022-05-09 05:34 UTC, aleksandrinvictor commented on crypto_sentiment_demo_app/models/base.py
> +    def get_model(cls, name: str, cfg: Dict[str, Any]) -> "ModelEngine":
fixed in 8d5c939

2022-05-09 05:36 UTC, aleksandrinvictor commented on crypto_sentiment_demo_app/models/bert/model.py
> +        if self.cfg["device"] == "gpu" and not torch.cuda.is_available():
Я бы не убирал возможность запуска на cpu, даже если на машине есть gpu. Как минимум для дебага это может пригодиться

2022-05-09 05:38 UTC, aleksandrinvictor commented on crypto_sentiment_demo_app/model_inference_api/Dockerfile
> +RUN curl -sLo ~/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh \
Для mvp пока может оставить конду? На второй этап все равно планирую добавить onnx инференс. Тогда можно будет убрать конду и образ взять маленький

2022-05-09 10:42 UTC, Yorko requested changes
Все в итоге получилось, но было больновато. Стоит отметить, что надо зачистить все прежние образы (просто переданный флаг --build все равно не все образы пересобирал, у меня model_scorer и frontend фэйлилсь). 

Не удалось завести GPU в образе, если это все же работает, надо уточнить инструкции. 
Надо существенно обновить ридми, а то приходилось догадываться, что как. 

И давай, может, переоткроем и будем напрямую в main лить?

2022-05-09 10:42 UTC, Yorko commented on crypto_sentiment_demo_app/models/bert/dataset.py
> +    :param cfg: model/preporcess config
```suggestion
    :param cfg: model/preprocess config
```

2022-05-09 10:42 UTC, Yorko commented on crypto_sentiment_demo_app/train/Dockerfile
> +WORKDIR /root
Не вижу, где локальные файлы добавляются. В частности, конфиги из `conf`.  Поменял флаг `device` у берта с `cpu` на `gpu` – это изменение не подхватилось. Пришлось заново собирать довольно немаленький образ

2022-05-09 10:42 UTC, Yorko commented on pyproject.toml
> +[tool.black]
Настройки flake8 вроде сюда же можно перетащить?

UPD. [нет](https://github.com/PyCQA/flake8/issues/234) :)

2022-05-09 10:42 UTC, Yorko commented on crypto_sentiment_demo_app/models/bert/model.py
> +        if self.cfg["device"] == "gpu" and not torch.cuda.is_available():
У меня в контейнере basic_image_train `torch.cuda.is_available()` False, и в итоге не CPU моделька обучалась. Я б добил все же, чтоб в докере GPU работала.

2022-05-09 10:42 UTC, Yorko commented on README.md
> + - run `USER=$(id -u) GROUP=$(id -g) docker compose --profile train up`. Model checkpoint will be saved in the path_to_model folder
Непонятно, где определяется `path_to_model` – надо уточнить, что в конфиге конкретной модели. 

У меня обучение воспроизвелось, но не сразу. FYI: пришлось поудалять все имеющиеся контейнеры и запустить с флагом `--build`. Также указанная команда у меня запускала еще и контейнер `model_inference_api`. 

Мелочь, но lightning жалуется, что даталодырю можно указать больше CPUs (The dataloader, val_dataloader 0, does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` (try 16 which is the number of cpus on this machine) in the `DataLoader` init to improve performance.)

2022-05-09 10:42 UTC, Yorko commented on crypto_sentiment_demo_app/models/bert/model.py
> +        if self.cfg["device"] == "gpu" and not torch.cuda.is_available():
да, давайте пока так, но точно надо будет облегчать образ, даже дебаггинг так очень долгий получается

2022-05-15 20:20 UTC, closed without merging