Feature/data provider
crypto-sentiment/crypto_sentiment_demo_app pull request #4
Opened 2022-05-12 07:05 UTC by Arsenaut

Добавил data_provider сервис, который будет забирать из базы информацию в нужном формате (среднее значение positive по дням, среднее значение positive за последние N часов, последние k новостей) и предоставлять её через API для фронтенда.

2022-05-12 11:42 UTC, Yorko requested changes
Круто! Замечания есть по мелочи, но в целом все стройно и красиво. 

пс. сорри, потащил сюда изменения краулера и mode_scorer, но это просто black & isort

2022-05-12 11:42 UTC, Yorko commented on crypto_sentiment_demo_app/frontend/streamlit_app.py
> +    today_average_sentiment = get_sentiment_score(24)
```suggestion
    today_average_sentiment = get_sentiment_score(n_hours=24)
```

2022-05-12 11:42 UTC, Yorko commented on crypto_sentiment_demo_app/frontend/streamlit_app.py
> +    endpoint_url = "http://data_provider:8002/positive_score/average_last_hours"
Лучше бы это в конфиги, и забирать методом а-ля [`crypto_sentiment_demo_app.utils.get_model_inference_api_endpoint`](https://github.com/crypto-sentiment/crypto_sentiment_demo_app/blob/main/crypto_sentiment_demo_app/utils.py#L76). Но учитывая, что streamlit – временный фронтенд, забьем

2022-05-12 11:42 UTC, Yorko commented on crypto_sentiment_demo_app/data_provider/schemas.py
> +from pydantic import BaseModel
`pydantic` в зависимости наверное надо?

2022-05-12 11:42 UTC, Yorko commented on crypto_sentiment_demo_app/data_provider/db_connector.py
> +        Returns average per day positive score for news from
Тут стоит указать формат строк `start_date` и `end_date`

2022-05-12 11:42 UTC, Yorko commented on crypto_sentiment_demo_app/data_provider/db_connector.py
> +        Returns average positive score for news from
Тут стоит указать формат строк `start_date` и `end_date`

2022-05-12 11:42 UTC, Yorko commented on crypto_sentiment_demo_app/data_provider/db_connector.py
> +    def get_top_k_news_titles(self, k) -> list:
Может, тут добавить флаг – доставать положительные или отрицательные новости? который прокинется в query_template.order_by ниже. Идея была, что фронтенд показывает топ-2 хорошие новости, топ-2 плохие и одну нейтральную

2022-05-12 11:42 UTC, Yorko commented on crypto_sentiment_demo_app/data_provider/db_connector.py
> +    def calc_avg_positive_last_n_hours_model_predictions(self, n) -> Optional[float]:
```suggestion
    def calc_avg_positive_last_n_hours_model_predictions(self, n_hours: int) -> Optional[float]:
```

2022-05-12 11:42 UTC, Yorko commented on crypto_sentiment_demo_app/data_provider/db_connector.py
> +        datetime_mark = datetime.datetime.now() - datetime.timedelta(hours=n)
```suggestion
        datetime_mark = datetime.datetime.now() - datetime.timedelta(hours=n_hours)
```

2022-05-18 11:23 UTC, aleksandrinvictor approved these changes
Все хорошо, оставил пару комментов

2022-05-18 11:23 UTC, aleksandrinvictor commented on crypto_sentiment_demo_app/data_provider/Dockerfile
> +COPY . /root
Может тут не нужно копировать папку в контейнер, в docker-compose все равно вся папка crypto_sentiment_demo_app маунтится?

2022-05-18 11:23 UTC, aleksandrinvictor commented on docker-compose.yml
> +      - model_inference_api
Думаю стоит добавить зависимость от data_provider и прописать healthcheck, чтобы фронт не обращался к data_provider, пока он не запущен

```suggestion
    depends_on:
      model_inference_api:
        condition: service_healthy
      data_provider: 
        condition: service_healthy
```

2022-05-18 11:23 UTC, aleksandrinvictor commented on crypto_sentiment_demo_app/data_provider/db_connector.py
> +        model_predictions table representation
Это пока не очень важно, но везде использованы numpydoc комменты, а мы вроде договаривались использовать sphinx. В будущем может не пройти проверку в CI

2022-05-27 12:16 UTC, Yorko commented
кажется, можно вливать изменения из main и мержить

2022-05-27 14:23 UTC, Arsenaut commented
> кажется, можно вливать изменения из main и мержить

Сделано

2022-05-27 14:57 UTC, Yorko approved these changes

2022-05-27 21:00 UTC, Yorko commented
Работает, запустил `docker compose -f docker-compose.yml --profile production up --build`, посмотрел список контейнеров `docker ps`, зашел во фронтенд: `docker exec -it <FRONT_CONTAINER_ID>  /bin/bash`. Там установил curl (`apt-get update; apt-get install curl`) и послал запрос к дата провайдеру:

```
curl --location --request GET 'http://data_provider:8002/news/top_k_news_titles' --header 'Content-Type: application/json' 
```

2022-05-27 21:00 UTC, Yorko commented
Работает, запустил `docker compose -f docker-compose.yml --profile production up --build`, посмотрел список контейнеров `docker ps`, зашел во фронтенд: `docker exec -it <FRONT_CONTAINER_ID>  /bin/bash`. Там установил curl (`apt-get update; apt-get install curl`) и послал запрос к дата провайдеру:

```
curl --location --request GET 'http://data_provider:8002/news/top_k_news_titles' --header 'Content-Type: application/json' 
```

2022-05-27 21:13 UTC, merged