Feature/frontend react wip
crypto-sentiment/crypto_sentiment_demo_app pull request #7
Opened 2022-05-19 14:16 UTC by LinkaG

Веб-модуль на основе react-приложения

2022-05-24 11:28 UTC, Yorko approved these changes
Все хорошо (хотя в код я не лез), по мелочи добавил замечания. Вот еще картинками:

<img src="https://habrastorage.org/webt/n2/xs/yg/n2xsygjw7gggqb4hrahumolh4ii.png" />

<img src="https://habrastorage.org/webt/6y/l1/ku/6yl1kujikuh71gs136a7cedihhw.png" />

2022-05-24 11:28 UTC, Yorko commented on crypto_sentiment_demo_app/frontend/src/components/News/index.js
> +      <h2 className="ml-20">Last News</h2>
```suggestion
      <h2 className="ml-20">Latest News</h2>
```

2022-05-24 11:28 UTC, Yorko commented on crypto_sentiment_demo_app/frontend/src/App.js
> +          <h1>Cryptosentiment</h1>
тут нужен пробел между логотипом и заголовком

2022-05-24 11:28 UTC, Yorko commented on crypto_sentiment_demo_app/frontend/src/App.js
> +          Bitcoin and other cryptocurrencies. The Crypto Sentiment Index varies
```suggestion
          Bitcoin and other cryptocurrencies. It varies
```

2022-05-24 11:28 UTC, Yorko commented on crypto_sentiment_demo_app/frontend/src/App.js
> +          in the range from 0 to 100, where a value of 0 means "Extreme
```suggestion
          in the range from 0 to 100, where a value of 0 means "Extremely
```

2022-05-24 11:28 UTC, Yorko commented on crypto_sentiment_demo_app/frontend/src/App.js
> +          Negative" while a value of 100 represents "Extreme Positive".
```suggestion
          Negative" while a value of 100 represents "Extremely Positive".
```

2022-05-24 11:28 UTC, Yorko commented on crypto_sentiment_demo_app/frontend/src/App.js
> +          of 0 means "Extreme Negative" while a value of 100 represents "Extreme
```suggestion
          of 0 means "Extremely Negative" while a value of 100 represents "Extremely
```

2022-05-25 16:55 UTC, Arsenaut requested changes
Вообще супер на мой вкус (код не ревьюил, чукча не фронтендер всё-таки), небольшие косяки по тексту Юра уже выделил, у меня вроде ни за что больше взгляд не зацепился. Можно ещё перенести в readme инструкцию запуска фронтенда отдельно как сервиса, но в целом непринципиально.

2022-05-25 16:57 UTC, Arsenaut approved these changes

2022-05-26 18:50 UTC, aleksandrinvictor approved these changes
Отличная работа, выглядит хорошо! Код тоже не могу поревьювить к сожалению)

Есть следующие предложения по улучшению интерфейса:
1. ![colors](https://user-images.githubusercontent.com/23315693/170553650-970833ec-2068-4397-b08f-abf4d1524954.png)
- У меня немного цепляется взгляд за прямоугольники (см. красные линий). Какую цель они выполняют? Может стоит их вообще убрать?
- Немного дезориентирует несоответствие цветов (см. синие и фиолетовые линии). Например, на барометре нейтральная и негативная зоны имеют серый цвет, однако соответсвующие кружки в блоке Historical Values не совпадают по цветам. Аналогично с кружками в блоке Latest News.
2. ![smiles](https://user-images.githubusercontent.com/23315693/170555077-403d7456-1403-404e-9e2c-bfe5bbcb4aca.png)
- В блоке index over time смайлики по цветам также не совпадают с цветами барометра для neutral и negative
- Думаю стоит заменить нейтральный смайлик на :neutral_face:, чтобы он отличался от позитивного (см. оранжевые линии)
- Возможно стоит поменять цвет футера на какой-нибудь темный, чтобы он отличался от основых блоков, примерно как тут: https://alternative.me/crypto/fear-and-greed-index/

2022-05-27 09:26 UTC, LinkaG commented
@aleksandrinvictor, спасибо за комментарий! Почти насчет всего согласна, кроме несоответствия цветов. На самом барометре серые области - это неактивные области. Когда значение индекса будет в нейтральном диапазоне, средняя область барометра окрасится в желтый, а остальные станут серыми, т.е. неактивными. Т.е. цвет меняется в зависимости от положения стрелки. В новостях и на графике цвета соответствуют значению индекса.

2022-06-02 08:49 UTC, Yorko commented
сорри, что подтащил сюда кучу изменений, но это просто pre-commit, хотелось проверить, что хуки из #10 действительно игнорируют JS-код. Работает

2022-06-02 15:55 UTC, Yorko commented
Верстку посмотрел еще раз, норм. Последний момент только: давай поблагодарим еще Hostkey и dstack.ai за ресурсы. 

Я б написал так примерно:

> Acknowledgements:
> -  We thank Nikita Zakharov and Yekaterina Kryukova for their contributions
> - We are grateful to [Hostkey](https://www.hostkey.ru/) and [dstack.ai](https://dstack.ai/) for providing computational resources

<img src="https://habrastorage.org/webt/kp/ee/b4/kpeeb4pnginmkk3482xciwm5i3m.png" />

2022-06-06 18:04 UTC, LinkaG commented on crypto_sentiment_demo_app/frontend/src/components/News/index.js
> +      <h2 className="ml-20">Last News</h2>
Пробел в заголовке добавила, заголовок в last news поправила, авторов добавила

2022-06-06 18:08 UTC, LinkaG commented on crypto_sentiment_demo_app/frontend/src/App.js
> +          in the range from 0 to 100, where a value of 0 means "Extreme
поправила описание

2022-06-06 18:15 UTC, merged